Algoritmo "Teste - Enquanto"

Var

   numero, soma : inteiro

Inicio

      escreva ("Digite o primeiro número: ")
      leia (numero)
      
      soma <- 0
      
      enquanto numero <> 0 faca
         soma <- soma + numero
         escreva ("Digite outro número: ")
         leia (numero)
      fimenquanto
      
      escreval
      escreval ("A soma dos números é: ", soma)


Fimalgoritmo