Algoritmo "Exercício - Múltiplos"

Var

   a, b : inteiro

Inicio

      escreva ("Digite o primeiro número: ")
      leia (a)
      escreva ("Digite os segundo número: ")
      leia (b)
      escreval
      
      se (a % b = 0) ou (b % a = 0) entao
         escreval ("Os números são múltiplos")
      senao
           escreval ("Os números não são múltiplos")
      fimse

Fimalgoritmo